name: Run coverage on PR
on: pull_request

jobs: 
    build-and-run-coverage:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            pull-requests: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: install Dependencies
              run: npm install
            - name: Build code
              run: npm run build
            - name: Report coverage
              uses:  davelosert/vitest-coverage-report-action@v2
