name: Run linter and tests on push
on:
  push:
    branches:
      - main

jobs:
  run-linter-and-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: npm install
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test
        
